### ISSUE TITLE
index.d.ts is missing from the npm package

### ISSUE THREAD

**Issue by scriby** [blackboard/protractor-sync#10]
I'm not sure what happened, but the index.d.ts appears to be missing from the npm package. It's the main entry point for typings in protractor-sync, so typings aren't usable at all without it.

![image](https://cloud.githubusercontent.com/assets/815188/26582334/a430d492-44f5-11e7-8896-69de7a1cb101.png)

PS: I also just noticed now that the copy:prepareModuleDefinition task in the gruntfile can be removed as it's not needed anymore.

**Comment by mindywhitsitt** [comment]
Thanks! We _did_ notice this issue when we finally sat down on Friday to start the process of incorporating this version of protractor-sync into Ultra. We don't know why it's happening either. The npmignore file looks right. But we will dig into it this week.

**Comment by mindywhitsitt** [comment]
Resolved by https://github.com/blackboard/protractor-sync/pull/12. Fix is present in version 5.1.4
