### ISSUE TITLE
Let's make it easier to test apps that don't include jQuery

### ISSUE THREAD

**Issue by scriby** [blackboard/protractor-sync#2]
Adding this issue to track discussion from https://github.com/blackboard/protractor-sync/commit/d418c0c567b195ffc7aa2507377f67521e74f496.

**Comment by scriby** [comment]
@steeltomato what do you think? Should I bring the automatic jquery injection back, or is there a different approach you'd prefer?

**Comment by sharp-bits** [comment]
My goal there was just to get jquery out of the dist/ stuff so it didn't need to be pushed to npm. It's probably ok to just read/inject it out of node_modules. I'm not opposed to putting it back.

**Comment by scriby** [comment]
Ok, will do, thanks.

**Comment by scriby** [comment]
This was resolved with #7
