### ISSUE TITLE
by.linkText() returns object of type By instead of ProtractorBy

### ISSUE THREAD

**Issue by mindywhitsitt** [blackboard/protractor-sync#22]
I think that by.linkText() used to return an object of type ProtractorBy, so we could write something like `.findElement(by.linkText('text of link'))`

But now that doesn't work anymore. I get a compile error like `Error:(117, 53) TS2345:Argument of type 'By' is not assignable to parameter of type 'string | ProtractorBy'.
  Type 'By' is not assignable to type 'ProtractorBy'.`

**Comment by scriby** [comment]
Looks like the type is wrong there. `ProtractorBy` is the static "by" class. Looks like the proper type is `Locator` instead.
