### ISSUE TITLE
need easy way to switch to new browser instance

### ISSUE THREAD

**Issue by mindywhitsitt** [blackboard/protractor-sync#27]
Previously when we wanted to leave one browser instance open (e.g. for inspection after a failing test) and fork a new one for continuing with other tests, we could do something like:

````
//Overwrite global variables so future tests will use new browser instance
(<any>global).browser = (<any>browser).forkNewDriverInstance();
(<any>global).element = browser.element;
````

I'm not sure how to do the equivalent thing in latest protractor-sync, and am wondering if we need to perhaps create a `setBrowser()` method to tell protractor-sync to start using the new browser created by forkNewDriverInstance()?

This is as you anticipated, @scriby. :)

**Comment by scriby** [comment]
I'll take a look soon to see what looks good here. I'm thinking a convenience method for this in protractor sync would be nice.
