### ISSUE TITLE
Make it easier to configure protractor-sync

### ISSUE THREAD

**Issue by scriby** [blackboard/protractor-sync#3]
Make it easier to set...

* Implicit wait time
* Retry interval
* Breakpoints
* Click retry interval
* Auto select stale elements
* Auto retry click

Allow configuration of which methods are disallowed.

I can work on this, just adding it here to track it.

**Comment by mindywhitsitt** [comment]
Sounds like a good idea.

**Comment by scriby** [comment]
This was resolved with #7
