### ISSUE TITLE
Kurt Waechter access..

### ISSUE THREAD

**Issue by shermaneric** [blackboard/protractor-sync#50]
Hey @scriby 
Just wanted to see if any issues giving Kurt Waechter access. He's on our team now and sits by Ken as well in Indy.

We may have some follow up questions for you as we're investigating using AWS Lambda to run our E2E tests in the future...

Thanks hope you are well!

**Comment by scriby** [comment]
No problem with me. I’m not an owner of the repo though :)

**Comment by shermaneric** [comment]
right on, thanks!  have a good weekend :)
