### ISSUE TITLE
README example doesn't work

### ISSUE THREAD

**Issue by sergeyKhristenko** [blackboard/protractor-sync#61]
Thank you for the library! I've just started exploring it. And the first thing that I did was to follow the installation steps in README. There are just plain arrow functions in the example, so I did the same and got '- Failed: Could not find the current asyncblock flow. Please make sure this method is called from an asyncblock context.'
Then I checked examples in /test/spec/protractor_sync_test.ts and there is a function 'createTest' which wraps all the tests in 'asyncblock context'. So should I do something similar in my tests? If so, why not to make it part of 'protractor-sync' test utils? Or maybe I just missed something obvious?

**Comment by scriby** [comment]
This looks like a reasonable request to me and would definitely help new users get up and running faster. I imagine we could provide a default implementation and if an end user wanted to do something special when an error occurs (like take a screenshot) they can implement their own createTest method.

**Comment by shermaneric** [comment]
I just spoke with @mindywhitsitt .  I'm working on a PR to update the documentation to have a working example for folks to plug and play with...

**Comment by shermaneric** [comment]
[This has been fixed with PR 63](https://github.com/blackboard/protractor-sync/pull/63)
Closing issue.
