### ISSUE TITLE
findElement should provide 'lazyElement' just like elementFinder does

### ISSUE THREAD

**Issue by sergeyKhristenko** [blackboard/protractor-sync#62]
Context:
The point is that protractor elementFinder doesn't initialize element immediately. The element will be initialized on demand. But protractor-sync findElement creates the element on init. Why it's bad? How would you recommend to implement pageObject using protractor-sync? And even in 'flat' cases, it could be not super cool (like in example below)

Steps to reproduce:
```
function createTest(fn: Function, errorMsg?: string) {
  return (done: Function) => {
    ab(
      () => {
        fn();
      },
      (err: any) => {
        if (errorMsg) {
          expect(err.message).toEqual(errorMsg);
        } else {
          expect((err && err.stack) || err || undefined).toBeUndefined();
        }
        done();
      }
    );
  };
}

describe('lazyElements', () => {

  it('language should be changed', createTest(() => {
    browserSync.getBrowser().waitForAngularEnabled(false);
    browserSync.get('https://translate.google.com/?hl=es');

    const langBtn: ElementFinderSync = elementSync.findElements('.sl-sugg-button-container > div')[0];
    const changeLang: ElementFinderSync = elementSync.findElement('#gt-swap');

    const langBefore = langBtn.getText();

    changeLang.click();

    const langAfter = langBtn.getText();

    expect(langBefore).not.toEqual(langAfter);
  }));
});
```

**Comment by scriby** [comment]
Thanks for your feedback. You point out an important difference between
protractor and protractor-sync and something we should definitely address
in the docs.

Nom-lazy element selection keeps in the spirit of protractor-sync. All the
commands you give protractor-sync execute immediately, which I think makes
test failures easier to reason about. It’s more straightforward to reason
about when commands are executing, and it’s also much easier to determine
which command caused a test failure, because the test itself won’t proceed
past what’s been executed by selenium. This makes stack traces from
failures easier to use as well.

Are you saying the example you provided doesn’t work? It seems like it
would to me.

As for the page object pattern, you can either just select the elements
when you want to use them, or you can memoize them within the class.

One pattern looks like this:

‘’’
class Page {
  constructor(private root = elementSync.findVisible(‘...’)){ }

  private controls = {
    langBtn: memoize(() => this.root.findVisible(‘...’))
  };

  changeLanguage() {
    this.controls.langBtn().click();

    return this;
  }
}
‘’’

Thanks,

Chris

**Comment by sergeyKhristenko** [comment]
Thank you for the quick response! And for the example! You are right that it would be nice to mention this in the doc(with page object example maybe). 
The example I provided doesn't work that I expect (text before should not equal text after). Are you saying that you have tried this and it worked for you? If so there might be an issue with my config or smth. If you haven't then can you please try to make it clear what is wrong. 
Thanks!

**Comment by scriby** [comment]
Your example code looks fine assuming that the button changes text immediately (synchronously). If it takes some time for the button to change text, you can use polledExpect (from protractor-sync) instead.

‘’’
polledExpect(() => langBtn.getText()).not.toEqual(langBefore);
‘’’

**Comment by sergeyKhristenko** [comment]
I've faced this issue with an Angular app and synchronization turning on. Generally, there shouldn't be an issue with 'element didn't change its state'.
But agree that the example was incorrect (also fixed selector).
But anyway, tried with polledExpect with the same result: 
```
describe('lazyElements', () => {
  it('lazyElements', createTest(() => {
      browserSync.getBrowser().waitForAngularEnabled(false);
      browserSync.get('https://translate.google.com/?hl=es');

      let langBtn: ElementFinderSync = elementSync.findElements('[aria-pressed="true"]')[0];
      const changeLang: ElementFinderSync = elementSync.findElement('#gt-swap');

      const langBefore = langBtn.getText();

      changeLang.click();

      polledExpect(() => langBtn.getText()).not.toEqual(langBefore);
    })
  );
});
```
And also tried with 'waitFor': 
```
      waitFor(() => {
        return langBtn.getText() !== langBefore;
      });

```

Also, it seems like there is no 'browserSync.sleep' method which is a common hot fix )))

**Comment by sergeyKhristenko** [comment]
And also if element initialized inside polledExpect it works fine:
```
describe('lazyElements', () => {
  it(
    'lazyElements',
    createTest(() => {
      browserSync.getBrowser().waitForAngularEnabled(false);
      browserSync.get('https://translate.google.com/?hl=es');

      let langBtn: ElementFinderSync = elementSync.findElements('[aria-pressed="true"]')[0];
      const changeLang: ElementFinderSync = elementSync.findElement('#gt-swap');

      const langBefore = langBtn.getText();

      changeLang.click();

      polledExpect(() => elementSync.findElements('[aria-pressed="true"]')[0].getText()).not.toEqual(langBefore);
    })
  );
});
```

**Comment by scriby** [comment]
I looked at the Google translate site, and it looks like the button text doesn’t change when the swap button is pressed if the input language is auto detected (which is the case when opening the page from scratch). Could this be why the test wasn’t working as expected?

**Comment by sergeyKhristenko** [comment]
I've explicitly specified language in URL. So there should be an option. But anyway I think I've found the cause.
Tried few cases:
1. When text changed in element - works fine;
2. When text changed with a sort of delay - works fine (and also in this example polledExpect won't work. only waitFor);
3. The issue with the provided example is that one element matches the selector and after click another element will match the selector.
4. The same as step3 but using Protractor to compare.

Cases: 
```
function createTest(fn: Function, errorMsg?: string) {
  return (done: Function) => {
    ab(
      () => {
        fn();
      },
      (err: any) => {
        if (errorMsg) {
          expect(err.message).toEqual(errorMsg);
        } else {
          expect((err && err.stack) || err || undefined).toBeUndefined();
        }
        done();
      }
    );
  };
}

describe('protractor-sync', () => {
  beforeEach(
    createTest(() => {
      browserSync.getBrowser().waitForAngularEnabled(false);
      browserSync.get('https://translate.google.com/#en/es');
    })
  );

  it(
    'works when the element changes its state',
    createTest(() => {
      browserSync.executeScript(() => {
        document.body.innerHTML = `<button onclick="setTimeout(()=>{\
          document.getElementById('btn').innerHTML = 'Hello World'},1000)"\
         id="btn">Click me</button>`;
      });

      let langBtn: ElementFinderSync = elementSync.findElement('#btn');

      const langBefore = langBtn.getText();

      langBtn.click();

      waitFor(() => {
        return langBtn.getText() !== langBefore;
      }, 4000);

      expect(langBtn.getText()).not.toEqual(langBefore);
    })
  );

  it(
    'works when another element will eventually match given selector',
    createTest(() => {
      let langBtn: ElementFinderSync = elementSync.findElement('#gt-lang-left [aria-pressed="true"]');
      const changeLang: ElementFinderSync = elementSync.findElement('#gt-swap');

      const langBefore = langBtn.getText();

      changeLang.click();

      waitFor(() => {
        return langBtn.getText() !== langBefore;
      }, 10000);

      expect(langBtn.getText()).not.toEqual(langBefore);
    })
  );
});

describe('using protractor', () => {
  it('should work when another element will match given selector', async () => {
    const langBtn: ElementFinder = $('#gt-lang-left [aria-pressed="true"]');
    const changeLang: ElementFinder = $('#gt-swap');

    await browser.waitForAngularEnabled(false);
    await browser.get('https://translate.google.com/#en/es');

    const langBefore = await langBtn.getText();

    await changeLang.click();

    await browser.wait(() => {
      return langBtn.getText().then(text => {
        return text !== langBefore;
      });
    });

    const langAfter = await langBtn.getText();

    expect(langAfter).not.toEqual(langBefore);
  });
});
```

**Comment by scriby** [comment]
I am on mobile and can’t check now but I have a feeling the translate app is actually just moving the DOM nodes instead of changing the text. So as long as you have a reference to the same DOM node its text isn’t going to change.

But if you re-select the node it will work.

Thanks,

Chris

**Comment by sergeyKhristenko** [comment]
Yes. Thank you! This is exactly what I was trying to say ). 
But I still expect it to work the same way as in protractor. In my test cases there is a case with protractor-sync (which keep referencing to the same node) and the same case with protractor(which is somehow reselect the node)

**Comment by scriby** [comment]
Oh, interesting, protractor must be re-selecting the node both times
getText is called. I thought it would select once and reuse the element.

For protractor-sync, the answer is definitely that the node needs to be
re-selected to refer to the left one after they swap.

Thanks,

Chris

**Comment by sergeyKhristenko** [comment]
Ok, so we are moved back to the first comment. How would page object implementation look like in this case? Should we explicitly duplicate a selector inside test? Or use a function inside the pageObject to get always 'fresh' element?
And again, this is a small tricky thing that is easy to miss and get false-positive or false-negative result in test.
I don't understand why it has been done this way? It works in protractor. And protractor-sync is a kind of a wrapper which wraps everything in asyncblock context and extend protractor with custom helpers. So I imagine that this elementFinder feature was affected by some helper function. If so, it doesn't have much sense because helper is an optional feature and elementFinder is a common feature.

**Comment by scriby** [comment]
I don’t think the protractor behavior is better, it’s just different. There
are also cases where you’re going to want to retain the element reference
even if the DOM changes around it.

Caching the element gives a perf boost, so It has some benefits as well.

As far as the page object pattern goes in this case, we could use the same
pattern I showed before and just take off the memoize, causing it to get
re-selected each time.

I agree this difference in behavior is suprising, so it would definitely
make sense to document the difference.

Thanks,

Chris

**Comment by shermaneric** [comment]
Thanks @scriby for responding on this!
I know you're busy.  So if you want, we can handle documenting these changes in a subsequent PR.  
Thanks!
Eric

**Comment by sergeyKhristenko** [comment]
I have just a few thoughts on this.
1. How could I know in advance when I should re-select element and when not? For example, I have a few tests without re-selecting (an element changes its text). And then we decided to refactor the app to make it works through the manipulating nodes instead of changing the text. Then my tests will be broken and I won't even know about it.
So it looks like that we should always re-select the elements.

2. If use finctions to define elements in pageObjet (like in the example you provided) it will work, but we will lose types. And it looks a bit weird: `page.controls.langBtn().getText()`. I imagine that langBtn should be a property but not a method.

3. What about perf boost? Did you measure it?

**Comment by scriby** [comment]
1. The behavior seen in the example app where it swaps DOM nodes is an exceedingly rare pattern. So, I would expect that generally we don't always re-select and just re-select in the rare instances where it is necessary. Please note that there are also instances where re-selecting the node can also cause breakages (for instance, if an element was inserted into a list, but you want to retain a reference to a previously selected item in the list). Also, I suspect that protractor only has this behavior for arrays... I expect it will cache single element lookups (could be wrong though).

2. Yeah, getters look like a good choice here, but unfortunately there's not a good pattern for memoizing getters that I'm aware of. For that reason I think we could consider an element selection pattern in this library that means "don't select the element until first use".

3. It's going to be a few milliseconds per selection, and more in some cases depending on latency. It can add up depending on what tests are doing. From a library perspective I think it's reasonable to optimize for performance here.

**Comment by sergeyKhristenko** [comment]
OK. I think there is not much sense to continue this discussion.
Thank you for the response! And for your efforts creating this library!

**Comment by mindywhitsitt** [comment]
Thanks for the useful discussion. We will update the documentation to try to make the behavior more clear. Closing the issue.
