### ISSUE TITLE
Updating/Maintaining chrome version 

### ISSUE THREAD

**Issue by shermaneric** [blackboard/protractor-sync#64]
Hey there,
I'm noticing right now when pushing changes that my local chrome (v65) is newer than the Chrome running on our CircleCI.
This makes things a tad tricky where we have to upgrade our Chromedriver version locally, but not check it into source control as it would break tests on CI.

Scouring the internets, I see solutions like this that [download the latest Chrome in](https://gist.github.com/Arjeno/8564d9643f16d072a85b9c9b5a9f7de0/revisions) before CI runs its tests.

Just musing out loud if folks had any other thoughts or other ways to tackle this syncing issue going forward.

Thanks in advance!
Eric

**Comment by mindywhitsitt** [comment]
Um, I think that's right. Either download the latest version or specifically download the version you want, maybe. How does Ultra handle this problem?

**Comment by shermaneric** [comment]
Right!
* So in Ultra/Blackboard land, we have a job that loads the latest version of Chrome on to docker containers at that time.  After each job completes, that version of Chrome now in the container is tagged.

* In our Ultra-UI runs, we select the tag above we wish to consume so we aren't automatically forced on to the latest version.

* We're also pinning the Chromedriver version in the Ultra-UI Project as well.

You make some good points, Mindy!  Let me think about what may be best here.  I could go either way.

**Comment by shermaneric** [comment]
I went ahead and made this PR to address.  [As always, feedback welcome!](https://github.com/blackboard/protractor-sync/pull/65)

@scriby not sure if you can see this ^ ?

**Comment by shermaneric** [comment]
FYI, this PR has been merged.
[I've also upped the protractor-sync version and published as 5.2.1](https://www.npmjs.com/package/protractor-sync)

Closing issue.
